### ISSUE TITLE
add fade for bottom of article

### ISSUE THREAD

**Issue by peccu** [peccu/clever-filter#10]
from: http://stackoverflow.com/a/11837686/514411

``` html
<div class="fadeout"></div>
```

``` css
.fadeout {
    position: relative; 
    bottom: 2em;
    height: 2em;
    background: -webkit-linear-gradient(
        rgba(255, 255, 255, 0) 0%,
        rgba(255, 255, 255, 1) 100%
    ); 
    background-image: -moz-linear-gradient(
        rgba(255, 255, 255, 0) 0%,
        rgba(255, 255, 255, 1) 100%
    );
    background-image: -o-linear-gradient(
        rgba(255, 255, 255, 0) 0%,
        rgba(255, 255, 255, 1) 100%
    );
    background-image: linear-gradient(
        rgba(255, 255, 255, 0) 0%,
        rgba(255, 255, 255, 1) 100%
    );
    background-image: -ms-linear-gradient(
        rgba(255, 255, 255, 0) 0%,
        rgba(255, 255, 255, 1) 100%
    );
} 
```

this technique can apply like/dislike button
